chmod a+x .
chmod a+x ./termux-root
chmod a+x ./configure~
chmod a+x ./autom4te.cache
chmod a+x ./hosttest.exe
chmod a+x ./ldebug.sh
chmod a+x ./regex-0.13
chmod a+x ./regex-0.13/configure
chmod a+x ./regex-0.13/config.sub
chmod a+x ./regex-0.13/config.guess
chmod a+x ./regex-0.13/config.status
chmod a+x ./regex-0.13/install-sh
chmod a+x ./configure
chmod a+x ./biosdisk
chmod a+x ./biosdisk/biosdisk.dll
chmod a+x ./include
chmod a+x ./config.sub
chmod a+x ./uninstallhead
chmod a+x ./utils
chmod a+x ./utils/bin2byte
chmod a+x ./windebug.sh
chmod a+x ./src
chmod a+x ./src/mkversion.old
chmod a+x ./src/extmod
chmod a+x ./src/mkdate.sh
chmod a+x ./src/mkmachine.sh
chmod a+x ./src/saveas
chmod a+x ./src/empty
chmod a+x ./sunos.sh
chmod a+x ./mkmenu.sh
chmod a+x ./misc
chmod a+x ./terminfo
chmod a+x ./terminfo/v
chmod a+x ./terminfo/l
chmod a+x ./terminfo/x
chmod a+x ./terminfo/r
chmod a+x ./terminfo/s
chmod a+x ./config.guess
chmod a+x ./buildinfo
chmod a+x ./buildinfo/configure
chmod a+x ./buildinfo/config.status
chmod a+x ./man2html
chmod a+x ./man2html/conf_script
chmod a+x ./man2html/hman.sh
chmod a+x ./plugins
chmod a+x ./plugins/examples
chmod a+x ./plugins/examples/macro2plug.sh
chmod a+x ./plugins/examples/mksrcnum.sh
chmod a+x ./plugins/examples/encodechar.sh
chmod a+x ./plugins/examples/mknss_dns.sh
chmod a+x ./x11
chmod a+x ./x11/startbed
chmod a+x ./x11/xbedone
chmod a+x ./x11/rmmenu
chmod a+x ./x11/Windows
chmod a+x ./bedkeys
chmod a+x ./libs-aarch64
chmod a+x ./libs
chmod a+x ./install-sh
chmod a+x ./config.status.lineno
chmod a+x ./linux.sh
chmod a+x ./debian
chmod a+x ./debian/rules
chmod a+x ./debian/postrm
chmod a+x ./debian/preinst
chmod a+x ./debian/postinst
chmod a+x ./debian/relog
chmod a+x ./debian/source
chmod a+x ./debian/bed
chmod a+x ./debian/bed/DEBIAN
chmod a+x ./debian/bed/DEBIAN/postrm
chmod a+x ./debian/bed/DEBIAN/preinst
chmod a+x ./debian/bed/DEBIAN/postinst
chmod a+x ./doc
chmod a+x ./doc/html3.sed.megahost.com
chmod a+x ./doc/mkindex.sh
chmod a+x ./progman
chmod a+x ./pkg
chmod a+x ./addmagic
