#define PROCEXEFILENAMEFORMAT "/proc/%d/exe"
#define HAS_FILE 1
/*#undef BRIEF_FILE */
/*#undef UNCOMPRESS_FILE */
#define HAS_MEMINFO 1
/*#undef OWNTRANSTIME*/
#define PRI_SIZE_T_MODIFIER "z"
#define REALLONGDOUBLE16
#define NOUNBLOCKSIGNALS 1
